### PR TITLE
488009: Update to Spring 4.2.4

### PR DESCRIPTION
**Pull request by olaf-otto**
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=488009. 
**Note:These changes have already been submitted for code review (eclipse gerrit)**

### CODE REVIEW

**Comment by charlesrgould** [comment]
What is the build branch for? I see it is 13 commits behind master and some of the changes here are implemented in master in [commit ac963cc](https://github.com/eclipse/gemini.blueprint/commit/ac963cca7caa31d4ee43a567a427763cccadc1b0). Can you help me understand which branch I should be focusing on if I want to use Gemini Blueprint with Spring 4.2.4?

**Comment by olaf-otto** [comment]
Hi @charlesrgould, thanks for asking! We're currently in the middle of cleaning up and releasing 2.0.0. This also involves cleaning up the various branches. Please excuse our mess in the meantime. The 2.0.0 release will feature Spring 4.2.x support, and will be available shortly (I suspect in the coming week).

If you want to try the version featuring 4.2.x support,  please use the "build" branch (https://github.com/eclipse/gemini.blueprint/tree/build). The upcoming release branches from there (release-2.x).

Regards,
Olaf

**Comment by anatoliy-balakirev** [comment]
Hi,
Not sure if this is a right place to ask, but how is it going with 2.0.0 release?

**Comment by olaf-otto** [comment]
Hi @anatoliy-balakirev Thanks for asking - we'r ready to release and finishing up a CI setup for direct deployment to maven central. I'm keeping people updated via the gemini-dev mailing list (http://dev.eclipse.org/mhonarc/lists/gemini-dev/).

**Comment by olaf-otto** [comment]
Gemini Blueprint 2.0.0 has been released today and contains these changes, see https://www.eclipse.org/gemini/blueprint/. Closing!

**Pull request closed without merging**
